const SupplierCategoryAction = {
    //Category
    FETCH_SEARCH_CATEGORY_START: 'FETCH_SEARCH_CATEGORY_START',
    FETCH_SEARCH_CATEGORY_SUCCESS: 'FETCH_SEARCH_CATEGORY_SUCCESS',
    FETCH_SEARCH_CATEGORY_ERROR: 'FETCH_SEARCH_CATEGORY_ERROR',

    DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',

    RESET_CATEGORY_START: 'RESET_CATEGORY_START',
    RESET_CATEGORY_SUCCESS: 'RESET_CATEGORY_SUCCESS',
    RESET_CATEGORY_ERROR: 'RESET_CATEGORY_ERROR',

    CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',
};

export default SupplierCategoryAction;