const SupplierCategoryAction = {
    FETCH_SEARCH_CATEGORY_START: 'FETCH_SEARCH_CATEGORY_START',
    FETCH_SEARCH_CATEGORY_SUCCESS: 'FETCH_SEARCH_CATEGORY_SUCCESS',
    FETCH_SEARCH_CATEGORY_ERROR: 'FETCH_SEARCH_CATEGORY_ERROR',

    DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_ERROR: 'DELETE_CATEGORY_ERROR',

    UNDO_CATEGORY_START: 'UNDO_CATEGORY_START',
    UNDO_CATEGORY_SUCCESS: 'UNDO_CATEGORY_SUCCESS',
    UNDO_CATEGORY_ERROR: 'UNDO_CATEGORY_ERROR',

    RESET_CATEGORY_START: 'RESET_CATEGORY_START',
    RESET_CATEGORY_SUCCESS: 'RESET_CATEGORY_SUCCESS',
    RESET_CATEGORY_ERROR: 'RESET_CATEGORY_ERROR',

    CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',

    UPDATE_CATEGORY_START: 'UPDATE_CATEGORY_START',
    UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_ERROR: 'UPDATE_CATEGORY_ERROR',
};

export default SupplierCategoryAction;