const ProvincesActions = {
    FETCH_PROVINCES_START: 'FETCH_PROVINCES_START',
    FETCH_PROVINCES_SUCCESS: 'FETCH_PROVINCES_SUCCESS',
    FETCH_PROVINCES_ERROR: 'FETCH_PROVINCES_ERROR',

    FETCH_DISTRICTS_START: 'FETCH_DISTRICTS_START',
    FETCH_DISTRICTS_SUCCESS: 'FETCH_DISTRICTS_SUCCESS',
    FETCH_DISTRICTS_ERROR: 'FETCH_DISTRICTS_ERROR',
    
    FETCH_WARDS_START: 'FETCH_WARDS_START',
    FETCH_WARDS_SUCCESS: 'FETCH_WARDS_SUCCESS',
    FETCH_WARDS_ERROR: 'FETCH_WARDS_ERROR',
};

export default ProvincesActions;