const SupplierAction = {
    FETCH_SEARCH_SUPPLIER_LIST: 'FETCH_SEARCH_SUPPLIER_LIST',
    FETCH_SEARCH_SUPPLIER_SUCCESS: 'FETCH_SEARCH_SUPPLIER_SUCCESS',
    FETCH_SEARCH_SUPPLIER_ERROR: 'FETCH_SEARCH_SUPPLIER_ERROR',

    GET_SUPPLIER_BY_ID_START: 'GET_SUPPLIER_BY_ID_START',
    GET_SUPPLIER_BY_ID_SUCCESS: 'GET_SUPPLIER_BY_ID_SUCCESS',
    GET_SUPPLIER_BY_ID_ERROR: 'GET_SUPPLIER_BY_ID_ERROR',

    CREATE_SUPPLIER_START: 'CREATE_SUPPLIER_START',
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_ERROR: 'CREATE_SUPPLIER_ERROR',

    UPDATE_SUPPLIER_START: 'UPDATE_SUPPLIER_START',
    UPDATE_SUPPLIER_SUCCESS: 'UPDATE_SUPPLIER_SUCCESS',
    UPDATE_SUPPLIER_ERROR: 'UPDATE_SUPPLIER_ERROR',

    CHANGE_STATUS_SUPPLIER_START: 'CHANGE_STATUS_SUPPLIER_START',
    CHANGE_STATUS_SUPPLIER_SUCCESS: 'CHANGE_STATUS_SUPPLIER_SUCCESS',
    CHANGE_STATUS_SUPPLIER_ERROR: 'CHANGE_STATUS_SUPPLIER_ERROR',

    UPDATE_STATUS_SUPP_DETAIL_START: 'UPDATE_STATUS_SUPP_DETAIL_START',
    UPDATE_STATUS_SUPP_DETAIL_SUCCESS: 'UPDATE_STATUS_SUPP_DETAIL_SUCCESS',
    UPDATE_STATUS_SUPP_DETAIL_ERROR: 'UPDATE_STATUS_SUPP_DETAIL_ERROR',

    DELETE_SUPPLIER_START: 'DELETE_SUPPLIER_START',
    DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
    DELETE_SUPPLIER_ERROR: 'DELETE_SUPPLIERP_DETAILR',
};

export default SupplierAction;