const SupplierAction = {
    FETCH_SUPPLIER_LIST: 'FETCH_SUPPLIER_LIST',
    FETCH_SUPPLIER_SUCCESS: 'FETCH_SUPPLIER_SUCCESS',
    FETCH_SUPPLIER_ERROR: 'FETCH_SUPPLIER_ERROR',

    SEARCH_SUPPLIER_START: 'SEARCH_SUPPLIER_START',
    SEARCH_SUPPLIER_SUCCESS: 'SEARCH_SUPPLIER_SUCCESS',
    SEARCH_SUPPLIER_ERROR: 'SEARCH_SUPPLIER_ERROR',

    DELETE_SUPPLIER_START: 'DELETE_SUPPLIER_START',
    DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
    DELETE_SUPPLIER_ERROR: 'DELETE_SUPPLIER_ERROR',

    CREATE_SUPPLIER_START: 'CREATE_SUPPLIER_START',
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_ERROR: 'CREATE_SUPPLIER_ERROR',

    UPDATE_SUPPLIER_START: 'UPDATE_SUPPLIER_START',
    UPDATE_SUPPLIER_SUCCESS: 'UPDATE_SUPPLIER_SUCCESS',
    UPDATE_SUPPLIER_ERROR: 'UPDATE_SUPPLIER_ERROR',

    RESET_SUPPLIER_START: 'RESET_SUPPLIER_START',
    RESET_SUPPLIER_SUCCESS: 'RESET_SUPPLIER_SUCCESS',
    RESET_SUPPLIER_ERROR: 'RESET_SUPPLIER_ERROR',
};

export default SupplierAction;