const SupplierAction = {
    FETCH_SEARCH_SUPPLIER_LIST: 'FETCH_SEARCH_SUPPLIER_LIST',
    FETCH_SEARCH_SUPPLIER_SUCCESS: 'FETCH_SEARCH_SUPPLIER_SUCCESS',
    FETCH_SEARCH_SUPPLIER_ERROR: 'FETCH_SEARCH_SUPPLIER_ERROR',

    DELETE_SUPPLIER_START: 'DELETE_SUPPLIER_START',
    DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
    DELETE_SUPPLIER_ERROR: 'DELETE_SUPPLIER_ERROR',

    CREATE_SUPPLIER_START: 'CREATE_SUPPLIER_START',
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_ERROR: 'CREATE_SUPPLIER_ERROR',

    CHANGE_STATUS_SUPPLIER_START: 'CHANGE_STATUS_SUPPLIER_START',
    CHANGE_STATUS_SUPPLIER_SUCCESS: 'CHANGE_STATUS_SUPPLIER_SUCCESS',
    CHANGE_STATUS_SUPPLIER_ERROR: 'CHANGE_STATUS_SUPPLIER_ERROR',

    RESET_SUPPLIER_START: 'RESET_SUPPLIER_START',
    RESET_SUPPLIER_SUCCESS: 'RESET_SUPPLIER_SUCCESS',
    RESET_SUPPLIER_ERROR: 'RESET_SUPPLIER_ERROR',
};

export default SupplierAction;