export const fetchSupplierList = [
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 1,
            supplierCode: "MM",
            supplierName: "Myanmar",
            category: "Danbury Municipal Airport",
            code: 252,
            debtCode: 87489893002,
            phone: "444 239 7750",
            email: "gjesteco0@reuters.com",
            city: "Nay Pyi Taw",
            district: "district test",
            ward: "Danbury",
            address: "93285 American Ash Court",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 2,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Iwo Jima Airport",
            code: 252,
            debtCode: 73089539051,
            phone: "475 843 9919",
            email: "rnoods1@nydailynews.com",
            city: "Balayong",
            district: "district test",
            ward: "ward test",
            address: "344 Arizona Park",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 3,
            supplierCode: "CN",
            supplierName: "China",
            category: "Springvale Airport",
            code: 251,
            debtCode: 91548522700,
            phone: "207 613 2432",
            email: "maksell2@google.co.uk",
            city: "Jiaomingsi",
            district: "district test",
            ward: "ward test",
            address: "535 Golf Center",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 4,
            supplierCode: "CN",
            supplierName: "China",
            category: "Albert Lea Municipal Airport",
            code: 253,
            debtCode: 22679840973,
            phone: "687 735 2661",
            email: "byarranton3@rambler.ru",
            city: "Jianlong",
            district: "district test",
            ward: "Albert Lea",
            address: "553 Erie Circle",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 5,
            supplierCode: "CL",
            supplierName: "Chile",
            category: "Marina Municipal Airport",
            code: 251,
            debtCode: 61820480885,
            phone: "910 871 0364",
            email: "ljoriot4@hugedomains.com",
            city: "Buin",
            district: "district test",
            ward: "Marina",
            address: "057 Monterey Point",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 6,
            supplierCode: "ID",
            supplierName: "Indonesia",
            category: "Sovetskiy Airport",
            code: 253,
            debtCode: 56589316800,
            phone: "304 214 2795",
            email: "jsvanetti5@yale.edu",
            city: "Negeriagung",
            district: "district test",
            ward: "Sovetskiy",
            address: "790 Scoville Plaza",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 7,
            supplierCode: "CN",
            supplierName: "China",
            category: "Theda Station Airport",
            code: 253,
            debtCode: 75023539520,
            phone: "941 439 8189",
            email: "rdugo6@miibeian.gov.cn",
            city: "Baizhang",
            district: "district test",
            ward: "Theda Station",
            address: "47474 Lotheville Center",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 8,
            supplierCode: "FR",
            supplierName: "France",
            category: "Montrose Regional Airport",
            code: 251,
            debtCode: 26782214361,
            phone: "201 119 5624",
            email: "bprobbin7@e-recht24.de",
            city: "La Garenne-Colombes",
            district: "Île-de-France",
            ward: "Montrose",
            address: "31 Duke Place",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 9,
            supplierCode: "TH",
            supplierName: "Thailand",
            category: "Schoolcraft County Airport",
            code: 253,
            debtCode: 75567389182,
            phone: "723 316 7577",
            email: "hjaggers8@examiner.com",
            city: "Si That",
            district: "district test",
            ward: "Manistique",
            address: "1 American Ash Point",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 10,
            supplierCode: "PL",
            supplierName: "Poland",
            category: "Sri Guru Ram Dass Jee International Airport",
            code: 252,
            debtCode: 77682309817,
            phone: "846 712 6120",
            email: "rcowlishaw9@answers.com",
            city: "Pieńsk",
            district: "district test",
            ward: "Amritsar",
            address: "726 Mockingbird Way",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 11,
            supplierCode: "CZ",
            supplierName: "Czech Republic",
            category: "Whangarei Airport",
            code: 252,
            debtCode: 78288808752,
            phone: "955 931 8893",
            email: "nwallworkea@cmu.edu",
            city: "Příbor",
            district: "district test",
            ward: "ward test",
            address: "61586 Tomscot Alley",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 12,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Gwalior Airport",
            code: 251,
            debtCode: 55222587339,
            phone: "457 855 2187",
            email: "rklousnerb@indiatimes.com",
            city: "Kambing",
            district: "district test",
            ward: "Gwalior",
            address: "634 Arapahoe Drive",
            status: 2,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 13,
            supplierCode: "NG",
            supplierName: "Nigeria",
            category: "Plymouth City Airport",
            code: 252,
            debtCode: 28398005429,
            phone: "940 706 4639",
            email: "ameerec@comsenz.com",
            city: "Jimeta",
            district: "district test",
            ward: "Plymouth",
            address: "7 Harbort Plaza",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 14,
            supplierCode: "SE",
            supplierName: "Sweden",
            category: "Sullivan County Airport",
            code: 253,
            debtCode: 69041780959,
            phone: "363 439 6872",
            email: "oketchend@prweb.com",
            city: "Eskilstuna",
            district: "Södermanland",
            ward: "Monticello",
            address: "2 Holy Cross Parkway",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 15,
            supplierCode: "PE",
            supplierName: "Peru",
            category: "Itapetinga Airport",
            code: 253,
            debtCode: 82203767985,
            phone: "362 258 0807",
            email: "tscarfee@imageshack.us",
            city: "Sinchao",
            district: "district test",
            ward: "Itapetinga",
            address: "5968 Moose Way",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 16,
            supplierCode: "CL",
            supplierName: "Chile",
            category: "Gualeguaychu Airport",
            code: 252,
            debtCode: 39367467913,
            phone: "214 541 5648",
            email: "gwilshiref@surveymonkey.com",
            city: "Pichilemu",
            district: "district test",
            ward: "Gualeguaychu",
            address: "510 Vernon Avenue",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 17,
            supplierCode: "PL",
            supplierName: "Poland",
            category: "Espinosa Airport",
            code: 253,
            debtCode: 54000166727,
            phone: "883 170 1758",
            email: "hwildgooseg@ft.com",
            city: "Sosnówka",
            district: "district test",
            ward: "Espinosa",
            address: "5 Granby Junction",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 18,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Rio Frio / Progreso Airport",
            code: 251,
            debtCode: 80591538109,
            phone: "409 205 8854",
            email: "spimerh@ca.gov",
            city: "Babo-Pangulo",
            district: "district test",
            ward: "Rio Frio / Progreso",
            address: "151 Grover Drive",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 19,
            supplierCode: "HK",
            supplierName: "Hong Kong",
            category: "Kaimana Airport",
            code: 253,
            debtCode: 78383601232,
            phone: "896 834 7040",
            email: "emccaulli@lulu.com",
            city: "Tuen Mun",
            district: "district test",
            ward: "Kaimana-Papua Island",
            address: "93368 Oxford Lane",
            status: 1,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 20,
            supplierCode: "UZ",
            supplierName: "Uzbekistan",
            category: "Hamburg-Finkenwerder Airport",
            code: 252,
            debtCode: 98197066837,
            phone: "920 498 5994",
            email: "lspadellij@latimes.com",
            city: "Chimboy Shahri",
            district: "district test",
            ward: "Hamburg",
            address: "0507 Rusk Circle",
            status: 2,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 21,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Skagway Airport",
            code: 252,
            debtCode: 48655515239,
            phone: "868 175 0386",
            email: "kgadsdonk@slideshare.net",
            city: "Mabilang",
            district: "district test",
            ward: "Skagway",
            address: "55103 Memorial Lane",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 22,
            supplierCode: "CN",
            supplierName: "China",
            category: "Bahía de los Ángeles Airport",
            code: 252,
            debtCode: 57494378895,
            phone: "456 458 5863",
            email: "arobelinl@answers.com",
            city: "Tiecun",
            district: "district test",
            ward: "Bahía de los Ángeles",
            address: "71101 Summerview Court",
            status: 2,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 23,
            supplierCode: "MX",
            supplierName: "Mexico",
            category: "Newton Municipal Airport",
            code: 253,
            debtCode: 99730181935,
            phone: "217 177 5626",
            email: "hfranchionim@sphinn.com",
            city: "Cuauhtemoc",
            district: "Tamaulipas",
            ward: "Newton",
            address: "5 Chinook Parkway",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 24,
            supplierCode: "AR",
            supplierName: "Argentina",
            category: "Luang Namtha Airport",
            code: 251,
            debtCode: 62768641066,
            phone: "128 399 3649",
            email: "chorlickn@sakura.ne.jp",
            city: "Centenario",
            district: "district test",
            ward: "Luang Namtha",
            address: "3482 Green Ridge Place",
            status: 2,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 25,
            supplierCode: "ID",
            supplierName: "Indonesia",
            category: "Tulum Naval Air Station",
            code: 251,
            debtCode: 87861697562,
            phone: "378 102 6155",
            email: "mtoffalonio@bizjournals.com",
            city: "Komi",
            district: "district test",
            ward: "Tulum",
            address: "6457 Maple Wood Lane",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 26,
            supplierCode: "SE",
            supplierName: "Sweden",
            category: "Boende Airport",
            code: 251,
            debtCode: 75317694583,
            phone: "957 491 3729",
            email: "treaganp@redcross.org",
            city: "Umeå",
            district: "Västerbotten",
            ward: "Boende",
            address: "8 Upham Pass",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 27,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Mataiva Airport",
            code: 251,
            debtCode: 34696450759,
            phone: "646 244 0053",
            email: "ccansdellq@china.com.cn",
            city: "Buan",
            district: "district test",
            ward: "ward test",
            address: "4 Hudson Point",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 28,
            supplierCode: "AL",
            supplierName: "Albania",
            category: "Coffeyville Municipal Airport",
            code: 251,
            debtCode: 60098416310,
            phone: "605 756 1045",
            email: "aprowtingr@biglobe.ne.jp",
            city: "Lushnjë",
            district: "district test",
            ward: "Coffeyville",
            address: "524 Washington Park",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 29,
            supplierCode: "RU",
            supplierName: "Russia",
            category: "Chris Hadfield Airport",
            code: 252,
            debtCode: 54516173821,
            phone: "955 886 9037",
            email: "tbarajass@free.fr",
            city: "Romanovskaya",
            district: "district test",
            ward: "Sarnia",
            address: "65 Hansons Drive",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 30,
            supplierCode: "SY",
            supplierName: "Syria",
            category: "São Gabriel Airport",
            code: 252,
            debtCode: 33877931726,
            phone: "930 823 8596",
            email: "ehaitliet@sitemeter.com",
            city: "‘Ayn an Nasr",
            district: "district test",
            ward: "São Gabriel",
            address: "5 Veith Park",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 31,
            supplierCode: "CN",
            supplierName: "China",
            category: "Multan International Airport",
            code: 251,
            debtCode: 88798964177,
            phone: "134 739 0763",
            email: "mspilstedu@tripadvisor.com",
            city: "Anzihao",
            district: "district test",
            ward: "Multan",
            address: "8351 Thierer Circle",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 32,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Guasopa Airport",
            code: 252,
            debtCode: 84883443773,
            phone: "442 183 1963",
            email: "yalgerv@disqus.com",
            city: "Limon",
            district: "district test",
            ward: "Woodlark (Muyua) Island",
            address: "25 Bluejay Junction",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 33,
            supplierCode: "FR",
            supplierName: "France",
            category: "Jersey Airport",
            code: 252,
            debtCode: 67489726096,
            phone: "173 512 7416",
            email: "ggoodbyw@google.it",
            city: "Caen",
            district: "Basse-Normandie",
            ward: "Saint Helier",
            address: "041 Bashford Junction",
            status: 1,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 34,
            supplierCode: "CN",
            supplierName: "China",
            category: "Costa Esmeralda Airport",
            code: 253,
            debtCode: 22394698452,
            phone: "281 857 1823",
            email: "kfussellx@netscape.com",
            city: "Sanrao",
            district: "district test",
            ward: "Tola",
            address: "0 Northridge Hill",
            status: 2,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 35,
            supplierCode: "CN",
            supplierName: "China",
            category: "Trombetas Airport",
            code: 252,
            debtCode: 16352718759,
            phone: "598 725 6742",
            email: "epokery@domainmarket.com",
            city: "Jiujiang",
            district: "district test",
            ward: "Oriximiná",
            address: "7 Canary Pass",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 36,
            supplierCode: "CN",
            supplierName: "China",
            category: "San Pedro Airport",
            code: 251,
            debtCode: 70595287070,
            phone: "743 362 7752",
            email: "jshellardz@reference.com",
            city: "Dakoutun",
            district: "district test",
            ward: "San Pedro de Urabá",
            address: "266 Eagan Park",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 37,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Chacalluta Airport",
            code: 253,
            debtCode: 34884503126,
            phone: "616 963 4462",
            email: "slassells10@answers.com",
            city: "Malabag",
            district: "district test",
            ward: "Arica",
            address: "1 Annamark Drive",
            status: 1,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 38,
            supplierCode: "PH",
            supplierName: "Philippines",
            category: "Dos Lagunas Airport",
            code: 253,
            debtCode: 41907192772,
            phone: "150 264 6630",
            email: "twadwell11@merriam-webster.com",
            city: "Kolape",
            district: "district test",
            ward: "Dos Lagunas",
            address: "4290 Bayside Center",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 39,
            supplierCode: "ST",
            supplierName: "Sao Tome and Principe",
            category: "Ruben Cantu Airport",
            code: 253,
            debtCode: 89885279450,
            phone: "814 487 3518",
            email: "gzelland12@prlog.org",
            city: "São Tomé",
            district: "district test",
            ward: "Santiago",
            address: "140 Farragut Park",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 40,
            supplierCode: "AR",
            supplierName: "Argentina",
            category: "Bordeaux-Mérignac Airport",
            code: 252,
            debtCode: 18795390272,
            phone: "164 468 8123",
            email: "dgovern13@nymag.com",
            city: "Tres Arroyos",
            district: "district test",
            ward: "Bordeaux/Mérignac",
            address: "5 Starling Alley",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 41,
            supplierCode: "CN",
            supplierName: "China",
            category: "Mc Cook Ben Nelson Regional Airport",
            code: 253,
            debtCode: 28191015809,
            phone: "581 877 4768",
            email: "hleband14@reddit.com",
            city: "Changqing",
            district: "district test",
            ward: "Mc Cook",
            address: "54 Brown Plaza",
            status: 1,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 42,
            supplierCode: "PT",
            supplierName: "Portugal",
            category: "Bob Baker Memorial Airport",
            code: 252,
            debtCode: 90017802525,
            phone: "316 840 6916",
            email: "sgulberg15@cbsnews.com",
            city: "Quinta da Courela",
            district: "Setúbal",
            ward: "Kiana",
            address: "730 Lakewood Circle",
            status: 1,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 43,
            supplierCode: "PE",
            supplierName: "Peru",
            category: "Bali Airport",
            code: 253,
            debtCode: 77268725551,
            phone: "725 394 7510",
            email: "hbalaisot16@phoca.cz",
            city: "Morropón",
            district: "district test",
            ward: "Bali",
            address: "6 Sunnyside Junction",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 44,
            supplierCode: "ID",
            supplierName: "Indonesia",
            category: "Herrera Airport",
            code: 251,
            debtCode: 30011958871,
            phone: "626 870 6214",
            email: "mwashbrook17@123-reg.co.uk",
            city: "Kalapanunggal",
            district: "district test",
            ward: "Campiña",
            address: "6 Barnett Junction",
            status: 2,
        },
    },
    {
        categorization: "Ngành",
        note: "Ghi chú",
        items: {
            id: 45,
            supplierCode: "ID",
            supplierName: "Indonesia",
            category: "Valdez Pioneer Field",
            code: 253,
            debtCode: 82378289752,
            phone: "916 569 3243",
            email: "nhannaby18@deliciousdays.com",
            city: "Ketanen",
            district: "district test",
            ward: "Valdez",
            address: "6867 Kingsford Drive",
            status: 2,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 46,
            supplierCode: "PE",
            supplierName: "Peru",
            category: "San Javier Airport",
            code: 252,
            debtCode: 60078986709,
            phone: "233 500 5108",
            email: "agiovannini19@csmonitor.com",
            city: "Nanchoc",
            district: "district test",
            ward: "San Javier",
            address: "7 Dwight Trail",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 47,
            supplierCode: "KR",
            supplierName: "South Korea",
            category: "Makini Airport",
            code: 252,
            debtCode: 33953375705,
            phone: "109 468 4349",
            email: "ucauston1a@hao123.com",
            city: "Gaigeturi",
            district: "district test",
            ward: "Makini",
            address: "78794 Green Ridge Hill",
            status: 1,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 48,
            supplierCode: "LV",
            supplierName: "Latvia",
            category: "Manono Airport",
            code: 252,
            debtCode: 21502895065,
            phone: "759 757 5116",
            email: "jmiddlemist1b@networkadvertising.org",
            city: "Smārde",
            district: "district test",
            ward: "Manono",
            address: "6339 Bultman Terrace",
            status: 2,
        },
    },
    {
        categorization: "Mục",
        note: "Ghi chú",
        items: {
            id: 49,
            supplierCode: "CN",
            supplierName: "China",
            category: "Zinder Airport",
            code: 253,
            debtCode: 99410428476,
            phone: "795 726 7084",
            email: "cmclaughlan1c@va.gov",
            city: "Maoya",
            district: "district test",
            ward: "Zinder",
            address: "3 Hovde Junction",
            status: 1,
        },
    },
    {
        categorization: "Nhóm",
        note: "Ghi chú",
        items: {
            id: 50,
            supplierCode: "BR",
            supplierName: "Brazil",
            category: "Surat Airport",
            code: 251,
            debtCode: 91254652364,
            phone: "586 958 7568",
            email: "abeminster1d@google.cn",
            city: "Itaparica",
            district: "district test",
            ward: "ward test",
            address: "17 Vera Way",
            status: 2,
        },
    },
];
