const AccountAction = {
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',

    ME_START: 'ME_START',
    ME_SUCCESS: 'ME_SUCCESS',
    ME_ERROR: 'ME_ERROR',

    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    REFRESH_TOKEN_START: 'REFRESH_TOKEN_START',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_ERROR: 'REFRESH_TOKEN_ERROR',
};

export default AccountAction;